/**
 * DENSE landing logo field — GENERATED, do not edit by hand.
 *
 * Regenerate with: python scripts/build-dense-logos.py
 * (edit scripts/dense-candidates.txt first).
 *
 * WHY THIS FILE EXISTS INSTEAD OF A CDN OF ICONS:
 * the landing page is a static export on Cloudflare Pages, and the hero holds
 * the LCP element. Loading 200+ <img> tags from theSVG or cdn.simpleicons.org
 * would put 200 third-party requests on the critical path, leak every visitor's
 * IP and User-Agent to that host, and make the page's most important screen
 * depend on someone else's uptime. Both icon packs are already dependencies of
 * this repo, so the same 220 brands cost zero network requests and work
 * offline.
 *
 * BRAND ACCURACY, which is the whole point of the verification tier:
 *   - simple-icons v16 REMOVED several brands for trademark reasons (Slack,
 *     OpenAI, AWS, Twilio, Heroku). Those come from lobehub instead.
 *   - lobehub has no Docker/PostgreSQL/Redis, so those come from simple-icons.
 *   - A brand present in neither pack is DROPPED by the generator, never
 *     approximated. `SiSlackware` is a Linux distribution, not Slack, and
 *     shipping a penguin under Slack's name is the exact plausible-looking
 *     wrong this project's tests exist to catch.
 */
import {
  SiAirbyte, SiAirtable, SiAkamai, SiAlgolia, SiAlibabacloud, SiAnsible, SiAnthropic,
  SiApache, SiApacheairflow, SiApachekafka, SiApachesolr, SiAppwrite, SiArgo, SiAsana,
  SiBigcommerce, SiBitbucket, SiBrevo, SiBun, SiCaddy, SiCircleci, SiClaude, SiClickhouse,
  SiClickup, SiCloudflare, SiCockroachlabs, SiCodecov, SiConsul, SiConvex, SiDatabricks,
  SiDatadog, SiDebian, SiDeno, SiDependabot, SiDevdotto, SiDigitalocean, SiDiscord,
  SiDocker, SiDocusaurus, SiDodopayments, SiDrizzle, SiElasticsearch, SiFacebook,
  SiFastly, SiFigma, SiFirebase, SiFramer, SiGit, SiGitbook, SiGithub, SiGitlab, SiGo,
  SiGooglecloud, SiGooglegemini, SiGrafana, SiHashnode, SiHelm, SiHetzner, SiHubspot,
  SiHuggingface, SiInstagram, SiIntercom, SiIstio, SiJenkins, SiJfrog, SiJupyter,
  SiKaggle, SiKubernetes, SiLemonsqueezy, SiLinear, SiLinux, SiMailchimp, SiMailgun,
  SiMedium, SiMeilisearch, SiMiro, SiMistralai, SiMixpanel, SiMongodb, SiMysql,
  SiNatsdotio, SiNeon, SiNetlify, SiNewrelic, SiNginx, SiNodedotjs, SiNomad, SiNotion,
  SiNumpy, SiObsidian, SiOpencv, SiOpenjdk, SiOpensearch, SiOpentelemetry, SiPaddle,
  SiPandas, SiPaypal, SiPerplexity, SiPlanetscale, SiPostgresql, SiPosthog, SiPrefect,
  SiPrisma, SiProducthunt, SiPrometheus, SiPython, SiPytorch, SiQdrant, SiRabbitmq,
  SiRazorpay, SiReadme, SiReddit, SiRedis, SiRender, SiReplicate, SiResend, SiRust,
  SiScaleway, SiScikitlearn, SiSentry, SiShopify, SiSketch, SiStripe, SiSubstack,
  SiSupabase, SiTelegram, SiTensorflow, SiTerraform, SiTiktok, SiTravisci, SiTrello,
  SiTurso, SiTypeform, SiTypescript, SiUbuntu, SiUpstash, SiVault, SiVercel, SiVultr,
  SiWise, SiWoocommerce, SiX, SiYoutube, SiZapier, SiZendesk, SiZoom,
} from "@icons-pack/react-simple-icons";
import {
  Adobe, AdobeFirefly, Aws, Azure, AzureAI, BaiduCloud, Baseten, Bedrock, Cerebras, Cline,
  Cohere, Colab, ComfyUI, Copilot, CrewAI, Cursor, DeepInfra, DeepMind, DeepSeek, Devin,
  Dify, ElevenLabs, Exa, Firecrawl, Fireworks, Gemma, GiteeAI, GithubCopilot, Glama,
  Gradio, Grok, Groq, IBM, Ideogram, Jina, Lambda, LangChain, LangGraph, LangSmith,
  Langfuse, LlamaIndex, LmStudio, Lovable, Make, Manus, Mastra, Midjourney, ModelScope,
  Moxt, N8n, Ollama, OpenAI, Poe, Qwen, Railway, Replit, Runway, SearXNG, SiliconCloud,
  Smithery, Snowflake, Suno, Tavily, Tencent, Together, Udio, V0, VertexAI, Wandb,
  Windsurf, WorkersAI, XAI, Zeabur,
} from "@lobehub/icons";

export type DenseLogo = {
  name: string;
  Component: React.ElementType;
  /** simple-icons: ask for the real brand fill. lobehub Mono: theme foreground. */
  brand: boolean;
};

export const denseLogos: DenseLogo[] = [
  { name: "Airbyte", Component: SiAirbyte, brand: true },
  { name: "Airflow", Component: SiApacheairflow, brand: true },
  { name: "Airtable", Component: SiAirtable, brand: true },
  { name: "Akamai", Component: SiAkamai, brand: true },
  { name: "Algolia", Component: SiAlgolia, brand: true },
  { name: "AlibabaCloud", Component: SiAlibabacloud, brand: true },
  { name: "Ansible", Component: SiAnsible, brand: true },
  { name: "Anthropic", Component: SiAnthropic, brand: true },
  { name: "Apache", Component: SiApache, brand: true },
  { name: "Appwrite", Component: SiAppwrite, brand: true },
  { name: "Argo", Component: SiArgo, brand: true },
  { name: "Asana", Component: SiAsana, brand: true },
  { name: "BigCommerce", Component: SiBigcommerce, brand: true },
  { name: "Bitbucket", Component: SiBitbucket, brand: true },
  { name: "Brevo", Component: SiBrevo, brand: true },
  { name: "Bun", Component: SiBun, brand: true },
  { name: "Caddy", Component: SiCaddy, brand: true },
  { name: "CircleCI", Component: SiCircleci, brand: true },
  { name: "Claude", Component: SiClaude, brand: true },
  { name: "ClickHouse", Component: SiClickhouse, brand: true },
  { name: "ClickUp", Component: SiClickup, brand: true },
  { name: "Cloudflare", Component: SiCloudflare, brand: true },
  { name: "CockroachDB", Component: SiCockroachlabs, brand: true },
  { name: "Codecov", Component: SiCodecov, brand: true },
  { name: "Consul", Component: SiConsul, brand: true },
  { name: "Convex", Component: SiConvex, brand: true },
  { name: "Databricks", Component: SiDatabricks, brand: true },
  { name: "Datadog", Component: SiDatadog, brand: true },
  { name: "Debian", Component: SiDebian, brand: true },
  { name: "Deno", Component: SiDeno, brand: true },
  { name: "Dependabot", Component: SiDependabot, brand: true },
  { name: "DevTo", Component: SiDevdotto, brand: true },
  { name: "DigitalOcean", Component: SiDigitalocean, brand: true },
  { name: "Discord", Component: SiDiscord, brand: true },
  { name: "Docker", Component: SiDocker, brand: true },
  { name: "Docusaurus", Component: SiDocusaurus, brand: true },
  { name: "Dodo", Component: SiDodopayments, brand: true },
  { name: "Drizzle", Component: SiDrizzle, brand: true },
  { name: "Elasticsearch", Component: SiElasticsearch, brand: true },
  { name: "Facebook", Component: SiFacebook, brand: true },
  { name: "Fastly", Component: SiFastly, brand: true },
  { name: "Figma", Component: SiFigma, brand: true },
  { name: "Firebase", Component: SiFirebase, brand: true },
  { name: "Framer", Component: SiFramer, brand: true },
  { name: "Gemini", Component: SiGooglegemini, brand: true },
  { name: "Git", Component: SiGit, brand: true },
  { name: "GitBook", Component: SiGitbook, brand: true },
  { name: "GitHub", Component: SiGithub, brand: true },
  { name: "GitLab", Component: SiGitlab, brand: true },
  { name: "Go", Component: SiGo, brand: true },
  { name: "GoogleCloud", Component: SiGooglecloud, brand: true },
  { name: "Grafana", Component: SiGrafana, brand: true },
  { name: "Hashnode", Component: SiHashnode, brand: true },
  { name: "Helm", Component: SiHelm, brand: true },
  { name: "Hetzner", Component: SiHetzner, brand: true },
  { name: "HubSpot", Component: SiHubspot, brand: true },
  { name: "HuggingFace", Component: SiHuggingface, brand: true },
  { name: "Instagram", Component: SiInstagram, brand: true },
  { name: "Intercom", Component: SiIntercom, brand: true },
  { name: "Istio", Component: SiIstio, brand: true },
  { name: "JFrog", Component: SiJfrog, brand: true },
  { name: "Jenkins", Component: SiJenkins, brand: true },
  { name: "Jupyter", Component: SiJupyter, brand: true },
  { name: "Kafka", Component: SiApachekafka, brand: true },
  { name: "Kaggle", Component: SiKaggle, brand: true },
  { name: "Kubernetes", Component: SiKubernetes, brand: true },
  { name: "LemonSqueezy", Component: SiLemonsqueezy, brand: true },
  { name: "Linear", Component: SiLinear, brand: true },
  { name: "Linux", Component: SiLinux, brand: true },
  { name: "Mailchimp", Component: SiMailchimp, brand: true },
  { name: "Mailgun", Component: SiMailgun, brand: true },
  { name: "Medium", Component: SiMedium, brand: true },
  { name: "MeiliSearch", Component: SiMeilisearch, brand: true },
  { name: "Miro", Component: SiMiro, brand: true },
  { name: "Mistral", Component: SiMistralai, brand: true },
  { name: "Mixpanel", Component: SiMixpanel, brand: true },
  { name: "MongoDB", Component: SiMongodb, brand: true },
  { name: "MySQL", Component: SiMysql, brand: true },
  { name: "NATS", Component: SiNatsdotio, brand: true },
  { name: "Neon", Component: SiNeon, brand: true },
  { name: "Netlify", Component: SiNetlify, brand: true },
  { name: "NewRelic", Component: SiNewrelic, brand: true },
  { name: "Nginx", Component: SiNginx, brand: true },
  { name: "Node.js", Component: SiNodedotjs, brand: true },
  { name: "Nomad", Component: SiNomad, brand: true },
  { name: "Notion", Component: SiNotion, brand: true },
  { name: "NumPy", Component: SiNumpy, brand: true },
  { name: "Obsidian", Component: SiObsidian, brand: true },
  { name: "OpenCV", Component: SiOpencv, brand: true },
  { name: "OpenJDK", Component: SiOpenjdk, brand: true },
  { name: "OpenSearch", Component: SiOpensearch, brand: true },
  { name: "OpenTelemetry", Component: SiOpentelemetry, brand: true },
  { name: "Paddle", Component: SiPaddle, brand: true },
  { name: "Pandas", Component: SiPandas, brand: true },
  { name: "PayPal", Component: SiPaypal, brand: true },
  { name: "Perplexity", Component: SiPerplexity, brand: true },
  { name: "PlanetScale", Component: SiPlanetscale, brand: true },
  { name: "PostHog", Component: SiPosthog, brand: true },
  { name: "PostgreSQL", Component: SiPostgresql, brand: true },
  { name: "Prefect", Component: SiPrefect, brand: true },
  { name: "Prisma", Component: SiPrisma, brand: true },
  { name: "ProductHunt", Component: SiProducthunt, brand: true },
  { name: "Prometheus", Component: SiPrometheus, brand: true },
  { name: "PyTorch", Component: SiPytorch, brand: true },
  { name: "Python", Component: SiPython, brand: true },
  { name: "Qdrant", Component: SiQdrant, brand: true },
  { name: "RabbitMQ", Component: SiRabbitmq, brand: true },
  { name: "Razorpay", Component: SiRazorpay, brand: true },
  { name: "Readme", Component: SiReadme, brand: true },
  { name: "Reddit", Component: SiReddit, brand: true },
  { name: "Redis", Component: SiRedis, brand: true },
  { name: "Render", Component: SiRender, brand: true },
  { name: "Replicate", Component: SiReplicate, brand: true },
  { name: "Resend", Component: SiResend, brand: true },
  { name: "Rust", Component: SiRust, brand: true },
  { name: "Scaleway", Component: SiScaleway, brand: true },
  { name: "ScikitLearn", Component: SiScikitlearn, brand: true },
  { name: "Sentry", Component: SiSentry, brand: true },
  { name: "Shopify", Component: SiShopify, brand: true },
  { name: "Sketch", Component: SiSketch, brand: true },
  { name: "Solr", Component: SiApachesolr, brand: true },
  { name: "Stripe", Component: SiStripe, brand: true },
  { name: "Substack", Component: SiSubstack, brand: true },
  { name: "Supabase", Component: SiSupabase, brand: true },
  { name: "Telegram", Component: SiTelegram, brand: true },
  { name: "TensorFlow", Component: SiTensorflow, brand: true },
  { name: "Terraform", Component: SiTerraform, brand: true },
  { name: "TikTok", Component: SiTiktok, brand: true },
  { name: "TravisCI", Component: SiTravisci, brand: true },
  { name: "Trello", Component: SiTrello, brand: true },
  { name: "Turso", Component: SiTurso, brand: true },
  { name: "TypeScript", Component: SiTypescript, brand: true },
  { name: "Typeform", Component: SiTypeform, brand: true },
  { name: "Ubuntu", Component: SiUbuntu, brand: true },
  { name: "Upstash", Component: SiUpstash, brand: true },
  { name: "Vault", Component: SiVault, brand: true },
  { name: "Vercel", Component: SiVercel, brand: true },
  { name: "Vultr", Component: SiVultr, brand: true },
  { name: "Wise", Component: SiWise, brand: true },
  { name: "WooCommerce", Component: SiWoocommerce, brand: true },
  { name: "X", Component: SiX, brand: true },
  { name: "YouTube", Component: SiYoutube, brand: true },
  { name: "Zapier", Component: SiZapier, brand: true },
  { name: "Zendesk", Component: SiZendesk, brand: true },
  { name: "Zoom", Component: SiZoom, brand: true },
  { name: "AWS", Component: Aws, brand: false },
  { name: "Adobe", Component: Adobe, brand: false },
  { name: "AdobeFirefly", Component: AdobeFirefly, brand: false },
  { name: "Azure", Component: Azure, brand: false },
  { name: "AzureAI", Component: AzureAI, brand: false },
  { name: "BaiduCloud", Component: BaiduCloud, brand: false },
  { name: "Baseten", Component: Baseten, brand: false },
  { name: "Bedrock", Component: Bedrock, brand: false },
  { name: "Cerebras", Component: Cerebras, brand: false },
  { name: "Cline", Component: Cline, brand: false },
  { name: "Cohere", Component: Cohere, brand: false },
  { name: "Colab", Component: Colab, brand: false },
  { name: "ComfyUI", Component: ComfyUI, brand: false },
  { name: "Copilot", Component: Copilot, brand: false },
  { name: "CrewAI", Component: CrewAI, brand: false },
  { name: "Cursor", Component: Cursor, brand: false },
  { name: "DeepInfra", Component: DeepInfra, brand: false },
  { name: "DeepMind", Component: DeepMind, brand: false },
  { name: "DeepSeek", Component: DeepSeek, brand: false },
  { name: "Devin", Component: Devin, brand: false },
  { name: "Dify", Component: Dify, brand: false },
  { name: "ElevenLabs", Component: ElevenLabs, brand: false },
  { name: "Exa", Component: Exa, brand: false },
  { name: "Firecrawl", Component: Firecrawl, brand: false },
  { name: "Fireworks", Component: Fireworks, brand: false },
  { name: "Gemma", Component: Gemma, brand: false },
  { name: "GitHubCopilot", Component: GithubCopilot, brand: false },
  { name: "GiteeAI", Component: GiteeAI, brand: false },
  { name: "Glama", Component: Glama, brand: false },
  { name: "Gradio", Component: Gradio, brand: false },
  { name: "Grok", Component: Grok, brand: false },
  { name: "Groq", Component: Groq, brand: false },
  { name: "IBM", Component: IBM, brand: false },
  { name: "Ideogram", Component: Ideogram, brand: false },
  { name: "Jina", Component: Jina, brand: false },
  { name: "Lambda", Component: Lambda, brand: false },
  { name: "LangChain", Component: LangChain, brand: false },
  { name: "LangGraph", Component: LangGraph, brand: false },
  { name: "LangSmith", Component: LangSmith, brand: false },
  { name: "Langfuse", Component: Langfuse, brand: false },
  { name: "LlamaIndex", Component: LlamaIndex, brand: false },
  { name: "LmStudio", Component: LmStudio, brand: false },
  { name: "Lovable", Component: Lovable, brand: false },
  { name: "Make", Component: Make, brand: false },
  { name: "Manus", Component: Manus, brand: false },
  { name: "Mastra", Component: Mastra, brand: false },
  { name: "Midjourney", Component: Midjourney, brand: false },
  { name: "ModelScope", Component: ModelScope, brand: false },
  { name: "Moxt", Component: Moxt, brand: false },
  { name: "N8n", Component: N8n, brand: false },
  { name: "Ollama", Component: Ollama, brand: false },
  { name: "OpenAI", Component: OpenAI, brand: false },
  { name: "Poe", Component: Poe, brand: false },
  { name: "Qwen", Component: Qwen, brand: false },
  { name: "Railway", Component: Railway, brand: false },
  { name: "Replit", Component: Replit, brand: false },
  { name: "Runway", Component: Runway, brand: false },
  { name: "SearXNG", Component: SearXNG, brand: false },
  { name: "SiliconFlow", Component: SiliconCloud, brand: false },
  { name: "Smithery", Component: Smithery, brand: false },
  { name: "Snowflake", Component: Snowflake, brand: false },
  { name: "Suno", Component: Suno, brand: false },
  { name: "Tavily", Component: Tavily, brand: false },
  { name: "TencentCloud", Component: Tencent, brand: false },
  { name: "Together", Component: Together, brand: false },
  { name: "Udio", Component: Udio, brand: false },
  { name: "V0", Component: V0, brand: false },
  { name: "VertexAI", Component: VertexAI, brand: false },
  { name: "WeightsAndBiases", Component: Wandb, brand: false },
  { name: "Windsurf", Component: Windsurf, brand: false },
  { name: "WorkersAI", Component: WorkersAI, brand: false },
  { name: "XAI", Component: XAI, brand: false },
  { name: "Zeabur", Component: Zeabur, brand: false },
];
